### ISSUE TITLE
[Bug]: fail to reset the input stream whose size > 2GB

### ISSUE THREAD

**Issue by Yu-Shawn** [sine-io/cosbench-sineio#44]
![bug1](https://github.com/user-attachments/assets/9e09d3ce-edb4-4293-a145-4a82f0ddbb54)

**Comment by kisscelia** [comment]
@Yu-Shawn thanks for reaching out.
the method in the sdk-v1 accept an int parameter
![image](https://github.com/user-attachments/assets/ff66b206-daaa-4406-8a12-836f2ce4fbdc)
so, please reduce the workers and try again, thank you.


Notice: 
Because of [Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025](https://github.com/aws/aws-sdk-java?tab=readme-ov-file#end-of-support-announcement), so the next milestone version of cosbench-sineio (v0.6.0.0 will be released at 2024.8.31) will be changed as follows:

1. sio renamed to siov1, and will not be maintained.
2. siov2 renamed to sio(use aws-sdk-java-v2), as a LTS Storage.
